AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Domain:
    Type: String
    Default: api.nr-amtcard.com

  CertificateArn:
    Type: String
    Default: arn:aws:acm:us-west-2:502679335954:certificate/cf004188-24cc-4268-9b8a-48a54b69a76b
Resources:

  Api:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        UsersTable: !Ref UsersTable
        Domain: !Ref Domain
        CertificateArn: !Ref CertificateArn
      TemplateURL:
        api/cloudformation.yml

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: card_id
          AttributeType: S
        - AttributeName: mundane_name
          AttributeType: S
        - AttributeName: persona_name
          AttributeType: S
      KeySchema:
        - AttributeName: card_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: mundane_name
          KeySchema:
            - AttributeName: mundane_name
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: persona_name
          KeySchema:
            - AttributeName: persona_name
              KeyType: HASH
          Projection:
              ProjectionType: ALL
